#!/usr/bin/env node
// Writes lib/tale-forms.js — the server-side view of every tale question in
// public/story.js TALES: how lib/stt-pick.js scores a transcript there and
// which words lib/stt-hints-core.js primes Whisper with. The browser script
// cannot be imported by the Vercel Edge function, so this copy is generated
// instead of hand-kept; tests/tales.test.js fails when it is stale.
//
//   node tools/tale-forms.js
const fs = require("fs");
const path = require("path");
const { TALES } = require(path.join(__dirname, "..", "public", "story.js"));

function expectedFor(node) {
  if (node.mode === "imitate") return { kind: "imitate", forms: [...node.accept], prefixes: [...(node.acceptPrefix || [])] };
  if (node.mode === "pick") return { kind: "choice", forms: node.choices.map((c) => ({ route: c.id, forms: [...c.forms] })) };
  if (node.mode === "open") return { kind: "empathy", forms: [] };
  if (node.mode === "exact" && node.count) return { kind: "count", n: node.count };
  return { kind: "free", forms: [] };
}

function buildTaleForms() {
  const forms = {}, hints = {};
  for (const tale of Object.values(TALES)) {
    for (const [id, node] of Object.entries(tale.nodes)) {
      if (node.kind !== "question") continue;
      forms[id] = expectedFor(node);
      if (node.hint) hints[id] = node.hint;
    }
  }
  return { forms, hints };
}

function render({ forms, hints }) {
  return [
    "// GENERATED by tools/tale-forms.js from public/story.js TALES — do not edit.",
    "// How the server scores each tale question and what Whisper is primed with.",
    `export const TALE_FORMS = ${JSON.stringify(forms, null, 1)};`,
    `export const TALE_HINTS = ${JSON.stringify(hints, null, 1)};`,
    "",
  ].join("\n");
}

if (require.main === module) {
  const out = path.join(__dirname, "..", "lib", "tale-forms.js");
  const data = buildTaleForms();
  fs.writeFileSync(out, render(data));
  console.log(`lib/tale-forms.js: ${Object.keys(data.forms).length} questions`);
}

module.exports = { buildTaleForms, render };
